version: '2'
services:
  challenge-app:
    container_name: challenge-app
    restart: always
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    stdin_open: true # docker run -i
    tty: true        # docker run -t
